name: Jar signing

#Checked in to test signing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.SIGNING_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

#      - name: Export
#        run: |
#          echo "${{secrets.SIGNING_KEY}}" > ~/.gradle/secring.gpg.b64
#          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      - name: Export
        run: |
          echo "${{secrets.SIGNING_KEY}} --"
      - name: Sign Jar
        run: ./gradlew :signMavenJavaPublication -PsigningKeyId=${{secrets.SIGNING_KEY_ID}} -PsigningPassword=${{secrets.SIGNING_PASSWORD}} -PsigningKey=${{secrets.SIGNING_KEY}}
