name: Jar signing

#Checked in to test signing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.SIGNING_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format SHORT
      - name: Export
        run: |
          echo use-agent >> ~/.gnupg/gpg.conf
          echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
          echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
          echo ${{ secrets.SIGNING_PASSWORD }} | gpg --export-secret-keys --batch --yes > ~/.gradle/secring.gpg
#          echo "${{ secrets.SIGNING_KEY }}" > ~/.gradle/secring
#          gpg --batch ~/.gradle/secring > ~/.gradle/secring.gpg
      - name: Sign Jar
        run: ./gradlew :signMavenJavaPublication -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password=${{ secrets.SIGNING_PASSWORD }} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
